### ISSUE TITLE
Incorrect prediction

### ISSUE THREAD

**Issue by Ngoroth** [bureaucratic-labs/dostoevsky#71]
`from typing import Dict

from dostoevsky.models import FastTextToxicModel
from dostoevsky.tokenization import RegexTokenizer

tokenizer = RegexTokenizer()

toxic_model = FastTextToxicModel(tokenizer=tokenizer)

messages = [
    'привет',
    'я люблю тебя!!',
    'малолетние дебилы'
]

results = toxic_model.predict(messages, k=2)

for message, sentiment in zip(messages, results):
    print(message, '->', sentiment)`

Output:
`привет -> {'normal': 0.9972950220108032, 'toxic': 0.0026416745968163013}
я люблю тебя!! -> {'toxic': 1.0000100135803223, 'normal': 1.0000003385357559e-05}
малолетние дебилы -> {'toxic': 1.0000100135803223, 'normal': 1.0000003385357559e-05}`

я люблю тебя!! has same toxic value with малолетние дебилы 

And if i'll change 
`toxic_model = FastTextToxicModel(tokenizer=tokenizer)` to `toxic_model = FastTextToxicModel(FastTextSocialNetworkModel(tokenizer=tokenizer))`
I getting exception:
`Traceback (most recent call last):
  File "E:/Projects/Toxicometer/ToxicityAnalyzer.py", line 18, in <module>
    results = toxic_model.predict(messages, k=2)
  File "E:\Projects\Toxicometer\venv\lib\site-packages\dostoevsky\models.py", line 84, in predict
    X = self.preprocess_input(sentences)
  File "E:\Projects\Toxicometer\venv\lib\site-packages\dostoevsky\models.py", line 72, in preprocess_input
    return [
  File "E:\Projects\Toxicometer\venv\lib\site-packages\dostoevsky\models.py", line 74, in <listcomp>
    token for token, _ in self.tokenizer.split(
AttributeError: 'FastTextSocialNetworkModel' object has no attribute 'split'

Process finished with exit code 1
`

**Comment by dveselov** [comment]
Hi,
I am aware of this issue. Currently, `FastTextToxicModel` is not ready to use.

**Comment by Ngoroth** [comment]
Thank you for response, i will wait impatiently
