### ISSUE TITLE
ModuleNotFoundError: No module named '_lzma'

### ISSUE THREAD

**Issue by alissiawells** [bureaucratic-labs/dostoevsky#83]
Почему не находится модуль lzma у Достоевского? 

Traceback (most recent call last):
  File "http_wrapper.py", line 202, in <module>
    from sentiment import Sentiment
  File "/local/opt/pksa/http_wrapper/sentiment.py", line 7, in <module>
    from dostoevsky.models import FastTextSocialNetworkModel
  File "/local/opt/pksa/env/lib/python3.6/site-packages/dostoevsky/models.py", line 9, in <module>
    from dostoevsky.data import DATA_BASE_PATH
  File "/local/opt/pksa/env/lib/python3.6/site-packages/dostoevsky/data/__init__.py", line 2, in <module>
    import lzma
  File "/usr/local/lib/python3.6/lzma.py", line 27, in <module>
    from _lzma import *
ModuleNotFoundError: No module named '_lzma'

**Comment by dveselov** [comment]
Hi, take a look at https://github.com/bureaucratic-labs/dostoevsky/issues/55
